### ISSUE TITLE
Statistics for Network.Transport

### ISSUE THREAD

**Issue by mboes** [haskell-distributed/network-transport#22]
_From @hyperthunk on December 18, 2012 13:44_

These would obviously be implementation dependent, so the API is likely to be rather loosely defined with `String` keys and so on. Making statistics available is likely to be very useful to administrators, particularly when trying to optimise the network topology for a distributed application. 

_Copied from original issue: haskell-distributed/distributed-process#98_

**Comment by qnikst** [comment]
Copy of #19
