### ISSUE TITLE
Block events from a particular EndPoint

### ISSUE THREAD

**Issue by avieth** [haskell-distributed/network-transport#32]
Requesting a new feature: offer a means of controlling input to an `EndPoint` from a particular `EndPointAddress`. Perhaps something like this:

```
data Accept = Accept | Block
modifyAcceptFrom :: EndPoint -> EndPointAddress -> (Accept -> IO (t, Accept)) -> IO t
```

`modifyAcceptFrom` facilitates querying and updating the policy for a given `EndPoint`, `EndPointAddress` pair. Set it to `Accept` and everything works as usual: the `EndPoint` will receive new connections and data from a peer at that `EndPointAddress`.

But what should be the semantics of `Block`? The motivation for this feature is to be able to stop reading from the socket to a given peer when using network-transport-tcp, perhaps because the local program is under heavy load and must slow down input from peers. This is related to another feature request: implementing `closeConnectionTo` #25 , which may be useful for similar reasons. Semantics may depend upon the `Reliability` of a connection (but how? I'm not completely sure).

I propose that after `modifyAcceptFrom localEndPoint remoteAddress f`, where `f` gives `(_, Block)`, `receive localEndPoint` will not give any events for connections from `remoteAddress` until it's unblocked (changed back to `Accept` via `modifyAcceptFrom`). It may however receive an `EventConnectionLost remoteAddress`. After the connection is unblocked, events originating from the peer while it was blocked will start to come in (`ConnectionOpened`, `ConnectionClosed`, `Received`). This would allow network-transport-tcp to stop reading from the socket when `Block`ed.

**Comment by avieth** [comment]
RFC @qnikst @edsko @dcoutts

**Comment by avieth** [comment]
How this might be realized in network-transport-tcp: https://github.com/haskell-distributed/network-transport-tcp/pull/45

**Comment by qnikst** [comment]
I'm not sure I have factored out if I like this approach or not.

It looks sensible, but require thoughtful check if  does conflict with n-t semantics or not. And unfortunately n-t semantics have missing pieces, so this may be rather hard to do. I'll try to recheck documentation if any conflicts can happen.

Another question is if this make sense on the n-t level, as far as I see not all implementations may have sane semantics for `Block`, at least for n-t-zmq this will be meaningless. Minor this that it will affect fast-path, but I'm not sure if the cost will be measurable. And if it's done on the n-t-$impl layer then nice API and tradeoffs can be decide on case by case basis.

One way to check is to cheat and check `CCI`  API, n-t API was highly inflicted by it's design, and maybe they already have something in that direction.

**Comment by avieth** [comment]
> Minor this that it will affect fast-path, but I'm not sure if the cost will be measurable.

Do you mean, you're concerned that it will affect performance in general? In the case of the n-t-tcp implementation, if the policy is always to accept then I'm fairly certain there will be no performance hit.

> And if it's done on the n-t-$impl layer then nice API and tradeoffs can be decide on case by case basis.

I'm OK with this too.

**Comment by qnikst** [comment]
> Do you mean, you're concerned that it will affect performance in general? 

Yes, and I agree that with n-t-tcp always accept policy will not introduce measurable overhead.

> I'm OK with this too.

Then I think it's the best way forward.

**Comment by avieth** [comment]
This has [developed over in network-transport-tcp](https://github.com/haskell-distributed/network-transport-tcp/pull/46). Perhaps that solution will eventually make it into the network-transport interface, perhaps not. In any case, closing this issue.
